name: Deploy Client

on:
  push:
    branches:
      - paul

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: '.'
          target: '/home/paul/app'

      - name: Creating .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          envs: REACT_APP_API_URL, REACT_APP_WEBSOCKET_URL
          script: |
            cd /home/paul/app
            touch .env
            echo REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} >> .env
            echo REACT_APP_WEBSOCKET_URL=${{ secrets.REACT_APP_WEBSOCKET_URL }} >> .env
            cat .env
      - name: Building the Client app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          envs: REACT_APP_API_URL, REACT_APP_WEBSOCKET_URL
          script: |
            cd /home/paul/app
            npm run build
            pm2 serve build/3000 --spa
